"""empty message

Revision ID: 964dba6ffce1
Revises: 922616500b99
Create Date: 2020-04-18 16:19:32.413540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964dba6ffce1'
down_revision = '922616500b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('show_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'show_date')
    # ### end Alembic commands ###
